### ISSUE TITLE
CircleCI deploy to Docker Hub

### ISSUE THREAD

**Issue by emcniece** [jonog/redalert#63]
https://hub.docker.com/r/jonog/redalert/tags/ appears to be 2 versions behind https://github.com/jonog/redalert/releases. Adding a deploy step to the `circle.yml` config might help keep these tags up to date.

https://circleci.com/docs/1.0/docker/ has info about adding deploy steps to https://github.com/jonog/redalert/blob/master/circle.yml.

```yml
deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push jonog/redalert
```
